<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tv</string>
		<string>tv.txt</string>
	</array>
	<key>name</key>
	<string>TV</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.tv</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.tv</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.tv</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.tv</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.tv</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-dash.tv</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?:(\d+)(x)(\d+))?[ \t]*(\|)[ \t]*(.+?)[ \t]*(--.*)?$</string>
			<key>name</key>
			<string>entry.tv</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\D</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.block.documentation.tv</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tv</string>
	<key>uuid</key>
	<string>C279AB60-63AF-45BC-AEB8-2FD1211AFFA0</string>
</dict>
</plist>
